#!/bin/bash
#
#VERSION       : 1.0.0
#PROGRAMMED BY : Rajesh Prashanth
#MODIFIED DATE : Tue Dec 26 01:19:29 IST 2017
#
#
./wrapper.sh $1
mkdir -p Calc && mv *in *out *dat* kpath ./Calc
mkdir Scripts && mv *sh *py Scripts
rm -rf output
